name: Maven Build with ZAP Proxy

on: [push, pull_request]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Start ZAP Proxy
        run: |
          docker run -u zap -d --name zap -p 8080:8080 owasp/zap2docker-stable zap.sh -daemon -port 8080 -host 0.0.0.0 -config api.disablekey=true -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true
          echo "Waiting for ZAP Proxy to start..."
          until $(curl --output /dev/null --silent --head --fail http://localhost:8080); do
              printf '.'
              sleep 5
          done
          echo "ZAP Proxy started."

      - name: Get ZAP Root CA Certificate and into Java Keystore
        run: |
          # Download ZAP CA Certificate
          curl -s http://localhost:8080/OTHER/core/other/rootcert/ > zaproxy.cer
          sudo keytool -importcert -file zaproxy.cer -keystore "${JAVA_HOME}/lib/security/cacerts" -alias zaproxy -storepass changeit -noprompt

      - name: Test with Maven
        run: |
          # Configure Maven to use ZAP as a proxy
          export MAVEN_OPTS="-Dhttp.proxyHost=localhost -Dhttp.proxyPort=8080 -Dhttps.proxyHost=localhost -Dhttps.proxyPort=8080"
          mvn clean test

      - name: Generate fake traffic to the target API to ensure its working properly
        run: |
          curl --proxy http://localhost:8080 https://www.deckofcardsapi.com/api/deck/new/shuffle/?deck_count=3


      - name: Generate ZAP Report
        run: curl -s http://localhost:8080/OTHER/core/other/htmlreport/ > zap_report.html

      - name: Upload ZAP Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_report.html

      - name: Upload Karate Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: karate-test-results
          path: target/karate-reports/